const mongoose = require("mongoose");
const Resume = require("../models/Resume");
const User = require("../models/User");

const createResume = async (req, res) => {
    try {
        const { user_id, file_url } = req.body;

        if (!user_id || !file_url) {
            return res.status(400).json({ message: "user_id and file_url are required" });
        }

        if (!mongoose.Types.ObjectId.isValid(user_id)) {
            return res.status(400).json({ message: "Invalid user_id" });
        }

        const userExists = await User.findById(user_id);
        if (!userExists) {
            return res.status(404).json({ message: "Referenced user does not exist" });
        }

        const resume = await Resume.create({ user_id, file_url });
        res.status(201).json(resume);
    } catch (error) {
        if (error.name === "ValidationError") {
            return res.status(400).json({ message: error.message });
        }
        res.status(500).json({ message: error.message });
    }
};

const getAllResumes = async (req, res) => {
    try {
        const filter = {};

        if (req.query.user_id) {
            if (!mongoose.Types.ObjectId.isValid(req.query.user_id)) {
                return res.status(400).json({ message: "Invalid user_id filter" });
            }
            filter.user_id = req.query.user_id;
        }

        const resumes = await Resume.find(filter).sort({ uploaded_at: -1 });
        res.status(200).json(resumes);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

const getResume = async (req, res) => {
    try {
        if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
            return res.status(400).json({ message: "Invalid resume id" });
        }

        const resume = await Resume.findById(req.params.id);
        if (!resume) {
            return res.status(404).json({ message: "Resume not found" });
        }

        res.status(200).json(resume);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

const updateResume = async (req, res) => {
    try {
        if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
            return res.status(400).json({ message: "Invalid resume id" });
        }

        // parsed_skills is system-generated by the parsing engine (R.1.2),
        // not something the user hand-edits. Only re-uploading a new file
        // makes sense as a user-initiated update.
        if (req.body.file_url === undefined) {
            return res.status(400).json({ message: "file_url is required to update" });
        }

        const resume = await Resume.findByIdAndUpdate(
            req.params.id,
            { file_url: req.body.file_url },
            { new: true, runValidators: true }
        );

        if (!resume) {
            return res.status(404).json({ message: "Resume not found" });
        }

        res.status(200).json(resume);
    } catch (error) {
        if (error.name === "ValidationError") {
            return res.status(400).json({ message: error.message });
        }
        res.status(500).json({ message: error.message });
    }
};

const deleteResume = async (req, res) => {
    try {
        if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
            return res.status(400).json({ message: "Invalid resume id" });
        }

        const resume = await Resume.findByIdAndDelete(req.params.id);
        if (!resume) {
            return res.status(404).json({ message: "Resume not found" });
        }

        res.status(200).json({ message: "Resume deleted" });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

module.exports = {
    createResume,
    getAllResumes,
    getResume,
    updateResume,
    deleteResume
};